#!/usr/bin/env python3
"""
Nerdbot CLI Bridge & Session Replay Utility
Enables terminal commands, Master Control daemons, and personal agents (Hermes, SAO, Eve)
to interact with authenticated browser sessions and execute automated tasks.
"""

import argparse
import json
import os
import sys
import urllib.request
import urllib.error

DEFAULT_AGENTS = {
    "hermes-legion": "http://localhost:8000/v1",
    "hermes-nukbox": "http://nukbox.local:8000/v1",
    "hermes-spine": "http://spine.local:8000/v1",
    "sao-core": "http://localhost:4177/v1",
    "openclaw": "http://localhost:18789/v1",
}

def check_agent(name: str, url: str) -> bool:
    models_url = f"{url.rstrip('/')}/models"
    try:
        req = urllib.request.Request(models_url, headers={"User-Agent": "Nerdbot-CLI/1.0"})
        with urllib.request.urlopen(req, timeout=3) as resp:
            data = json.loads(resp.read().decode())
            models = [m.get("id") for m in data.get("data", [])] if "data" in data else []
            print(f"  [ONLINE] {name} ({url}) -> Models: {', '.join(models[:3]) or 'ok'}")
            return True
    except Exception as e:
        print(f"  [OFFLINE] {name} ({url}) -> {e}")
        return False

def ping_fleet():
    print("\n--- Pinging Personal Agent Fleet ---")
    online = 0
    for name, url in DEFAULT_AGENTS.items():
        if check_agent(name, url):
            online += 1
    print(f"\nResult: {online}/{len(DEFAULT_AGENTS)} agent nodes reachable.\n")

def replay_session_request(curl_command: str):
    """Executes a replay request generated by Nerdbot's browser_extract_session tool."""
    print(f"Executing authenticated session replay:\n{curl_command}")
    os.system(curl_command)

def main():
    parser = argparse.ArgumentParser(description="Nerdbot CLI & Session Bridge")
    subparsers = parser.add_subparsers(dest="command")

    # Fleet ping
    subparsers.add_parser("fleet", help="Ping all configured personal agent nodes")

    # Dispatch to agent
    ask_parser = subparsers.add_parser("ask", help="Send prompt to a personal agent node")
    ask_parser.add_argument("prompt", help="Prompt or task for the agent")
    ask_parser.add_argument("--agent", default="hermes-legion", choices=list(DEFAULT_AGENTS.keys()), help="Target agent")
    ask_parser.add_argument("--model", default="default", help="Model ID")

    # Replay session
    replay_parser = subparsers.add_parser("replay", help="Execute an authenticated cURL command from Nerdbot")
    replay_parser.add_argument("curl_file_or_string", help="cURL command string or file path")

    args = parser.parse_args()

    if args.command == "fleet":
        ping_fleet()
    elif args.command == "replay":
        cmd = args.curl_file_or_string
        if os.path.exists(cmd):
            with open(cmd, "r", encoding="utf-8") as f:
                cmd = f.read()
        replay_session_request(cmd)
    elif args.command == "ask":
        base_url = DEFAULT_AGENTS.get(args.agent, "http://localhost:8000/v1")
        url = f"{base_url.rstrip('/')}/chat/completions"
        payload = {
            "model": args.model,
            "messages": [{"role": "user", "content": args.prompt}],
            "temperature": 0.7,
        }
        try:
            req = urllib.request.Request(
                url,
                data=json.dumps(payload).encode("utf-8"),
                headers={"Content-Type": "application/json", "User-Agent": "Nerdbot-CLI/1.0"},
            )
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read().decode())
                reply = data["choices"][0]["message"]["content"]
                print(f"\n[{args.agent}]:\n{reply}\n")
        except Exception as e:
            print(f"Error querying {args.agent}: {e}", file=sys.stderr)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
